name: Release

on:
  push:
    branches:
      - main

permissions: read-all # Declare default permissions as read only.

jobs:
  release:
    name: Release
    uses: inigomarquinez/reusable-workflows/.github/workflows/release.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
